site_name: The Cheat Sheet
site_url: https://thecheatsheet.readthedocs.io/
nav:
    - Home: index.md
    - About: about.md
    - Docker: 
        - Build: 'docker/build.md'
        - Volumes: 'docker/volumes.md'
    - Kubernetes: 
        - Minikube: 'kubernetes/minikube.md'
        - Pods: 'kubernetes/pods.md'
        - Labels: 'kubernetes/labels.md'
theme: 
    name: readthedocs
    highlightjs: true
